### ISSUE TITLE
UI Update: Banners

### ISSUE THREAD

**Issue by nedredmond** [nedredmond/dsa-ui#36]
# UI Update: Banners

---

## Summary

  This is the issue for creating base UI components for Banners as part of our reworked UI design.

  For more context, see
  - [the Design overhaul draft](https://docs.google.com/document/d/1BtEZEZCsRnEZnOTk36FbQYtjL6hDBLwCYh3xdZ6DBBo/edit#)
  - [this slack thread](https://dsa-ntc.slack.com/archives/CF8B9MENT/p1666442798832979)

  We may want to create these base components in the DSA UI package.
  

### Designs:
- [ ] [Info](https://www.figma.com/file/1Hty7YjMHXRHPwbESKUBf1/mydsa-public-01?node-id=174%3A8593) with svg from heroicons
- [ ] [Alert](https://www.figma.com/file/1Hty7YjMHXRHPwbESKUBf1/mydsa-public-01?node-id=174%3A9807)
- [ ] [Error](https://www.figma.com/file/1Hty7YjMHXRHPwbESKUBf1/mydsa-public-01?node-id=174%3A9807)

## Relevant areas

> What areas of the code or services are affected by this? Filling this out helps project
> maintainers properly triage the issue. Leave unchecked if unsure.

- [x] User interface
- [ ] Web server
- [ ] ActionKit integration
- [ ] Keycloak integration ([dsaID](https://github.com/dsausa-internal/dsaid))
- [ ] Developer tooling and documentation
- [ ] Other (describe below)

## Linked issues and Pull Requests

> Link to any related issues here.
