### ISSUE TITLE
UI Update: Account creation screen

### ISSUE THREAD

**Issue by nedredmond** [nedredmond/dsa-ui#41]
# UI Update: Account creation screen

---

## Summary

  This is the issue for redesigning the Account creation screen for our reworked UI design.

  For more context, see
  - [the Design overhaul draft](https://docs.google.com/document/d/1BtEZEZCsRnEZnOTk36FbQYtjL6hDBLwCYh3xdZ6DBBo/edit#)
  - [this slack thread](https://dsa-ntc.slack.com/archives/CF8B9MENT/p1666442798832979)

  This may involve creating new base WebComponents in the DSA UI package.
  

### Designs:
- [Figma](https://www.figma.com/file/1Hty7YjMHXRHPwbESKUBf1/mydsa-public-01?node-id=174%3A9597)
- Includes yellow alert and red error banner

## Relevant areas

> What areas of the code or services are affected by this? Filling this out helps project
> maintainers properly triage the issue. Leave unchecked if unsure.

- [x] User interface
- [ ] Web server
- [ ] ActionKit integration
- [ ] Keycloak integration ([dsaID](https://github.com/dsausa-internal/dsaid))
- [ ] Developer tooling and documentation
- [ ] Other (describe below)

## Linked issues and Pull Requests

> Link to any related issues here.
